### ISSUE TITLE
cannot import name 'write_txt' from 'whisper.utils' 

### ISSUE THREAD

**Issue by rcoenen** [yinruiqing/pyannote-whisper#7]
python -m pyannote_whisper.cli.transcribe data/afjiv.wav --model tiny --diarization True

results in:
ImportError: cannot import name 'write_txt' from 'whisper.utils'

**Comment by ravenwareltd** [comment]
There was a commit that renamed all of imports from the whisper UTILS library. 

 "txt": WriteTXT,
        "vtt": WriteVTT,
        "srt": WriteSRT,
        "tsv": WriteTSV,
        "json": WriteJSON,

Can anyone cater for these ?
